<#
.SYNOPSIS
Configures the model provider once for both the in-game MOD and the Web guide.

.DESCRIPTION
Prompts for any missing values, hides the API key while typing, and writes
.local\set-provider.ps1. Start-InGameGuide.ps1 and Start-WebGuide.ps1 load
that file automatically, so the provider is configured once per clone. The
.local directory is excluded by .gitignore, so the key is never committed.
Environment variables already set in the current session override the file.

.PARAMETER Provider
Provider kind: openai (OpenAI-compatible) or ollama (local).

.PARAMETER Model
Model name, for example gpt-4o-mini or llama3.2.

.PARAMETER BaseUrl
Optional OpenAI-compatible base URL, for example https://your-endpoint/v1.

.PARAMETER ApiKey
API key for GUIDE_PROVIDER=openai. When omitted, the script prompts with
hidden input. The key is never printed.

.PARAMETER Force
Overwrite an existing provider configuration.
#>
[CmdletBinding()]
param(
    [ValidateSet('openai', 'ollama')][string]$Provider,
    [string]$Model,
    [string]$BaseUrl,
    [string]$ApiKey,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$RepoRoot = Split-Path -Parent $PSScriptRoot
$LocalDirectory = Join-Path $RepoRoot '.local'
$ConfigPath = Join-Path $LocalDirectory 'set-provider.ps1'

if ((Test-Path -LiteralPath $ConfigPath -PathType Leaf) -and -not $Force) {
    throw "provider configuration already exists: $ConfigPath; re-run with -Force to replace it"
}

function Read-PlainTextValue {
    param(
        [Parameter(Mandatory = $true)][string]$Prompt,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Default = ''
    )

    $Answer = Read-Host -Prompt $Prompt
    if ([string]::IsNullOrWhiteSpace($Answer)) {
        return $Default
    }
    return $Answer.Trim()
}

function Read-HiddenSecret {
    param([Parameter(Mandatory = $true)][string]$Prompt)

    $SecureValue = Read-Host -Prompt $Prompt -AsSecureString
    $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
    try {
        return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($BSTR)
    } finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($BSTR)
    }
}

function ConvertTo-SingleQuotedPowerShellLiteral {
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Value)

    return "'" + $Value.Replace("'", "''") + "'"
}

if (-not $Provider) {
    $Provider = Read-PlainTextValue -Prompt 'Provider (openai or ollama, default openai)' -Default 'openai'
}
$Provider = $Provider.Trim().ToLowerInvariant()
if ($Provider -ne 'openai' -and $Provider -ne 'ollama') {
    throw "Provider must be openai or ollama, got: $Provider"
}

if (-not $Model) {
    $Model = Read-PlainTextValue -Prompt 'Model name (for example gpt-4o-mini or llama3.2)' -Default ''
}
if ([string]::IsNullOrWhiteSpace($Model)) {
    throw 'Model name is required'
}
$Model = $Model.Trim()

if ($Provider -eq 'openai') {
    if (-not $BaseUrl) {
        $BaseUrl = Read-PlainTextValue -Prompt 'Custom OpenAI-compatible base URL (press Enter to skip)' -Default ''
    }
    if ($BaseUrl) {
        $BaseUrl = $BaseUrl.Trim().TrimEnd('/')
        $ParsedBaseUrl = $null
        $ValidBaseUrl = [System.Uri]::TryCreate(
            $BaseUrl,
            [System.UriKind]::Absolute,
            [ref]$ParsedBaseUrl
        ) -and $ParsedBaseUrl.Scheme -in @('http', 'https')
        if (-not $ValidBaseUrl) {
            throw "Base URL must be an absolute http(s) URL: $BaseUrl"
        }
    }
    if (-not $ApiKey) {
        $ApiKey = Read-HiddenSecret -Prompt 'API key (input is hidden)'
    }
    if ([string]::IsNullOrWhiteSpace($ApiKey)) {
        throw 'API key is required when Provider is openai'
    }
}

$null = New-Item -ItemType Directory -Path $LocalDirectory -Force
$ConfigLines = New-Object System.Collections.Generic.List[string]
$ConfigLines.Add('# Generated by scripts\Set-GuideProvider.ps1; this directory is excluded by .gitignore.')
$ConfigLines.Add('$env:GUIDE_PROVIDER = ' + (ConvertTo-SingleQuotedPowerShellLiteral -Value $Provider))
$ConfigLines.Add('$env:GUIDE_MODEL = ' + (ConvertTo-SingleQuotedPowerShellLiteral -Value $Model))
if ($BaseUrl) {
    $ConfigLines.Add('$env:GUIDE_BASE_URL = ' + (ConvertTo-SingleQuotedPowerShellLiteral -Value $BaseUrl))
}
if ($ApiKey) {
    $ConfigLines.Add('$env:OPENAI_API_KEY = ' + (ConvertTo-SingleQuotedPowerShellLiteral -Value $ApiKey))
}
$ConfigText = ($ConfigLines -join [System.Environment]::NewLine) + [System.Environment]::NewLine
[System.IO.File]::WriteAllText($ConfigPath, $ConfigText, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Provider configuration saved: $ConfigPath"
Write-Host "Provider: $Provider"
Write-Host "Model: $Model"
if ($BaseUrl) {
    Write-Host "Base URL: $BaseUrl"
}
if ($ApiKey) {
    Write-Host 'API key: set (value hidden)'
}
Write-Host 'Start scripts load this file automatically; session environment variables still override it.'
